# Generated by Django 3.2 on 2021-07-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imge',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nicname',
            new_name='nickname',
        ),
    ]
